server:
  host: 127.0.0.1
  port: 8085
  timeout:
    server: 30s
    read: 15s
    write: 10s
    idle: 5s
rabbitmq:
  host: 127.0.0.1
  port: 5672
  user: guest
  password: guest
  queue: myqueue
  retryInterval: 60s
  maxRetries: 10